
CONFIGURE_VIEWADAPTOR_TRACE = False
CONFIGURE_MAINWINDOW_TRACE_COMMUNICATION= False
CONFIGURE_MAINWINDOW_TRACE = False
CONFIGURE_COMMUNICATOR_TRACE = False
CONFIGURE_APPLICATION_TRACE = False
CONFIGURE_MAIN_TRACE = False

CONFIGURE_VIEWADAPTOR_RETRANSLATE_KEYS = True
CONFIGURE_SLEEPED_OPTIMIZATION = True
CONFIGURE_CONSOLE_RETRANSLATE = True 