"""Runtime protocol primitives for isolated ZenCad script evaluation."""

from zencad.runtime.scene_protocol import (
    CURRENT_PROTOCOL_VERSION,
    FileSnapshotBundle,
    PayloadIntegrityError,
    ProtocolError,
    SceneObjectRecord,
    SceneSnapshot,
    SupersededGenerationError,
    UnsupportedProtocolVersion,
    decode_brep,
    decode_snapshot_frame,
    encode_brep,
    encode_snapshot_frame,
    ensure_current_generation,
    select_snapshot_transport,
)
from zencad.runtime.runner_protocol import RunnerMessage
from zencad.runtime.runner_supervisor import RunnerSupervisor
from zencad.runtime.scene_patch_protocol import (
    MAX_SCENE_PATCH_FRAME_BYTES,
    MAX_SCENE_PATCH_OBJECT_ID_BYTES,
    MAX_SCENE_PATCH_UPDATES,
    SCENE_PATCH_PROTOCOL_VERSION,
    SceneObjectPatch,
    ScenePatch,
    ScenePatchCoalescer,
    ScenePatchSequenceError,
    SupersededScenePatchError,
    UnsupportedScenePatchVersion,
    decode_scene_patch_frame,
    encode_scene_patch_frame,
    ensure_current_scene_patch,
)

__all__ = [
    "CURRENT_PROTOCOL_VERSION",
    "FileSnapshotBundle",
    "PayloadIntegrityError",
    "ProtocolError",
    "SceneObjectRecord",
    "SceneSnapshot",
    "SupersededGenerationError",
    "UnsupportedProtocolVersion",
    "decode_brep",
    "decode_snapshot_frame",
    "encode_brep",
    "encode_snapshot_frame",
    "ensure_current_generation",
    "select_snapshot_transport",
    "RunnerMessage",
    "RunnerSupervisor",
    "MAX_SCENE_PATCH_FRAME_BYTES",
    "MAX_SCENE_PATCH_OBJECT_ID_BYTES",
    "MAX_SCENE_PATCH_UPDATES",
    "SCENE_PATCH_PROTOCOL_VERSION",
    "SceneObjectPatch",
    "ScenePatch",
    "ScenePatchCoalescer",
    "ScenePatchSequenceError",
    "SupersededScenePatchError",
    "UnsupportedScenePatchVersion",
    "decode_scene_patch_frame",
    "encode_scene_patch_frame",
    "ensure_current_scene_patch",
]
